# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: purple
  
# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Personal website of Christelinda Laureijs.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "right"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    show_search: false
    show_theme_chooser: false

# Site footer
footer:
  copyright:
    notice: 'I made this site with the *blogdown* package, Hugo and Netlify.
    If you want to learn more about how it was made, or adapt it, check out [its repository on GitHub!](https://github.com/christelinda-laureijs/personal-website)'
# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
